# fly.toml file generated for postgres-ha-example on 2020-12-22T12:44:02-06:00

app = "md-pg"

# stop accepting new connections while existing sessions complete
kill_signal = "SIGTERM"
# allow 5 minutes to cleanly shutdown
kill_timeout = 300

[env]
PRIMARY_REGION = "dfw"

[checks.role]
type     = "script"
interval = 60000
timeout  = 10000
command  = "flycheck"
args     = [ "role" ]
restart_limit = 0

[checks.pg]
type         = "script"
interval     = 30000
timeout      = 10000
grace_period = "10s"
command      = "flycheck"
args         = [ "pg" ]
restart_limit = 0

[checks.vm]
type     = "script"
interval = 30000
timeout  = 10000
command  = "flycheck"
args     = [ "vm" ]
restart_limit = 0

[experimental]
private_network = true
enable_consul   = true
auto_rollback   = false

[metrics]
port = 9187
path = "/metrics"

[mount]
source      = "pg_data"
destination = "/data"
